name: Deploy on GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - uses: actions/checkout@v4
      - name: Install and Build
        run: |
          npm ci
          npm run build
      - name: Install and Build (sample)
        working-directory: ./sample
        run: |
          npm ci
          npm run build
          npm run export
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./sample/game
          user_name: 'github-actions'
          user_email: '41898282+github-actions[bot]@users.noreply.github.com'
